#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
#
# Run all dotfiles installers.
set -e

if [[ -z "$ZSH_VERSION" ]]; then
	echo "You need to install ZSH!"
fi

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
git ls-tree --name-only -r HEAD | grep install.sh | grep -v vim | while read -r installer; do
	echo "› ${installer}..."
	zsh -c "$installer"
done

# do vim last
git ls-tree --name-only -r HEAD | grep install.sh | grep vim | while read -r installer; do
	echo "› ${installer}..."
	zsh -c "$installer"
done

reset

