#!/usr/bin/env zsh

zinit light zinit-zsh/z-a-submods

zinit ice atpull="!git reset --hard"
zinit load sean-brandt/enhancd

zinit for \
    changyuheng/fz \
    chrissicool/zsh-256color \
    bckim92/zsh-autoswitch-conda \
    laggardkernel/git-ignore \
    lukechilds/zsh-nvm \
    MichaelAquilina/zsh-history-filter \
    unixorn/git-extra-commands \
    zpm-zsh/autoenv \
    zpm-zsh/clipboard \
    zpm-zsh/colorize \
    zpm-zsh/colors \
    olets/zsh-abbr \
    wolffaxn/brew-zsh-plugin \
    hschne/fzf-git \
    andrewferrier/fzf-z \
    Aloxaf/fzf-tab \
    mdumitru/git-aliases \
    reegnz/jq-zsh-plugin \
    droctothorpe/kubecolor \
    ELLIOTTCABLE/rbenv.plugin.zsh \
    hcgraf/zsh-sudo \
    lukechilds/zsh-nvm \
    hlissner/zsh-autopair \
    zsh-users/zsh-history-substring-search \
    from="gh-r" mv="exa* -> exa" fbin ogham/exa \
    DarrinTisdale/zsh-aliases-exa
# wait lucid load='![[ "${KUBERNETES_MASTER}x" != "x" ]]' unload='[[ -z "${KUBERNETES_MASTER}" ]]' unixorn/kubectx-zshplugin

zinit ice lucid
zinit snippet OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh

zinit ice from="gh-r" fbin="fzf" wait lucid
zinit load junegunn/fzf-bin

zinit ice wait lucid
zinit load rupa/z

zinit ice as"program" from"gh-r" mv"bat* -> bat" pick"bat/bat"
zinit light sharkdp/bat
alias more="bat"
alias less="bat"
alias cat="bat"

zinit ice as"command" from"gh-r" mv"ripgrep* -> rg" pick"rg/rg"
zinit light BurntSushi/ripgrep

zinit ice as"program" from"gh-r" mv"delta* -> delta" pick"delta/delta"
zinit light dandavison/delta
git config --global core.pager "delta --dark --hunk-style=plain"

zinit ice as"program" pick"$ZPFX/bin/git-*" make"PREFIX=$ZPFX" wait lucid src="etc/git-extras-completion.zsh"
zinit light tj/git-extras

zinit ice wait"1" lucid atinit"zpcompinit; zpcdreplay" atload"FAST_HIGHLIGHT[chroma-git]=\"chroma/-ogit.ch\""
zinit light zdharma/fast-syntax-highlighting

zinit ice wait"1" lucid atload"!_zsh_autosuggest_start"
zinit load zsh-users/zsh-autosuggestions

zinit add-fpath -f ~/.zsh_custom/functions
for i in ~/.zsh_custom/functions/*; do autoload -Uz $(basename $i); done

zinit ice pick="async.zsh" src="pure.zsh"
zinit load sindresorhus/pure


