#!/usr/bin/env zsh

zinit light zinit-zsh/z-a-bin-gem-node
zinit light zinit-zsh/z-a-as-monitor
zinit light zinit-zsh/z-a-submods

zinit ice atpull="!git reset --hard"
zinit load b4b4r07/enhancd

zinit for \
    changyuheng/fz \
    chrissicool/zsh-256color \
    bckim92/zsh-autoswitch-conda \
    laggardkernel/git-ignore \
    lukechilds/zsh-nvm \
    MichaelAquilina/zsh-history-filter \
    wait lucid atload='_zsh_autosuggest_start' zsh-users/zsh-autosuggestions \
    zdharma/fast-syntax-highlighting \
    unixorn/git-extra-commands \
    zpm-zsh/autoenv \
    zpm-zsh/clipboard \
    zpm-zsh/colorize \
    zpm-zsh/colors \
    olets/zsh-abbr \
    wolffaxn/brew-zsh-plugin \
    hschne/fzf-git \
    andrewferrier/fzf-z \
    Aloxaf/fzf-tab \
    mdumitru/git-aliases \
    reegnz/jq-zsh-plugin \
    droctothorpe/kubecolor \
    ELLIOTTCABLE/rbenv.plugin.zsh \
    hcgraf/zsh-sudo \
    lukechilds/zsh-nvm \
    zsh-users/zsh-history-substring-search \
    from="gh-r" mv="exa* -> exa" fbin ogham/exa \
    DarrinTisdale/zsh-aliases-exa
# wait lucid load='![[ "${KUBERNETES_MASTER}x" != "x" ]]' unload='[[ -z "${KUBERNETES_MASTER}" ]]' unixorn/kubectx-zshplugin

zinit ice wait lucid
zinit snippet OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh

zinit ice from="gh-r" fbin="fzf" wait lucid
zinit load junegunn/fzf-bin

zinit ice wait lucid
zinit load rupa/z

zplugin ice as"program" pick"bin/git-dsf" wait lucid
zplugin load zdharma/zsh-diff-so-fancy

zinit ice as"program" pick"$ZPFX/bin/git-*" make"PREFIX=$ZPFX" wait lucid src="etc/git-extras-completion.zsh"
zinit light tj/git-extras

zinit ice pick="async.zsh" src="pure.zsh"
zinit load sindresorhus/pure
